version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/client/node_modules
      - /app/node_modules
      - .:/app
    environment:
      - JWT_SECRET=boiler
      - DATABASE_INFO=mongodb+srv://jaab2021:KxerqPauBRCzufbi@cluster0.eiyfi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority