version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/client/node_modules
      - /app/node_modules
      - .:/app
    env_file:
      - docker-var.env